---
title: "GTExPortal"
output: md_document
---


Get data from GTEx portal https://gtexportal.org/home/


```
curl -o samples.txt https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt
curl -o subjects.txt https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt
curl -L genes.tsv https://osf.io/5sxvt/download > ensembl_genes.tsv
```

If you need to install packages, run the following chunk

```{r eval = F}

## Install tidyverse and lubridate

#install.packages("forcats")
#install.packages("tidyr")
#install.packages("dplyr")
#install.packages("lubridate")


```

Load required backages

```{r setup, message = F}

library(forcats)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)

```

Create the subjects file

```{r prep data}

subjects <- read.table("../data/subjects.txt", header = T, sep = "\t") %>%
  mutate_if(is.integer, as.factor) %>%
  mutate(SEX = fct_recode(SEX, "Male" = "1", "Female" = "2"),
         SEX = factor(SEX, levels = c("Female" , "Male")),
         DTHHRDY = fct_recode(DTHHRDY, "Ventilator Case" = "0",
                                       "Violent and fast death" = "1",
                                       "Fast death of natural causes" = "2",
                                       "Intermediate death" = "3",
                                       "Slow death" = "4"))

head(subjects)
```

Create the sampes file

```{r}

samples <- read.table("../data/samples.txt", header = T, sep = "\t") 
head(samples)
samples2 <- samples %>%
  select(SAMPID, SMTS, SMNABTCH, SMNABTCHD, SMGEBTCHT, SMAFRZE, SMCENTER, SMRIN, SMATSSCR) %>%
  drop_na() %>%
  mutate(SMNABTCHD = lubridate::mdy(SMNABTCHD),
         SAMPID2 = SAMPID) %>%
  separate(SAMPID2, into = c("one", "two"), sep = "-") %>%
  mutate(SUBJID = paste(one, two, sep = "-")) %>%
  select(SUBJID, SAMPID, SMTS, SMNABTCH, SMNABTCHD, SMGEBTCHT, SMAFRZE, SMCENTER, SMRIN, SMATSSCR) %>%
  right_join(subjects, ., by = "SUBJID")
head(samples2)
```
PLot the data

```{r, eval = F}
ggplot(subjects, aes(x = SEX)) +
  geom_bar(stat = "count")

ggplot(subjects, aes(x = AGE)) +
  geom_bar(stat = "count")

ggplot(subjects, aes(x = DTHHRDY)) +
  geom_bar(stat = "count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

ggplot(subjects, aes(x = AGE, fill = DTHHRDY)) +
  geom_bar(stat = "count") +
  facet_wrap(~SEX)
```
Check the genes file

```{r}
genes <- read.table("../data/ensembl_genes.tsv", sep = "\t",  header = T, fill = T)
head(genes)
```

Save the subject and sample files

```{r}
write.csv(subjects, "../data/subjects.csv", row.names = F)
write.csv(samples2, "../data/samples.csv", row.names = F)
```

