---
title: "recount3"
output: html_document
params: 
  #myproject: "MUSCLE"
  myproject: "HEART"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r recount3}
library(tidyverse)
library(recount3)
library(lubridate)

# get GTEx heart data
human_projects <- available_projects(organism = "human")

# enter yes

head(human_projects)
tail(human_projects)

gtex <- subset(human_projects,
                     project == params$myproject  & 
                       file_source == "gtex" & 
                       project_type == "data_sources" )

head(gtex)


rse_gtex <- create_rse(gtex)
rse_gtex

# format data for DESEq2


colData <- colData(rse_gtex) %>% 
  as.data.frame()  %>%
  filter(gtex.run_acc != "NA",
         gtex.smnabtcht != "RNA isolation_PAXgene Tissue miRNA") %>%
  dplyr::select(external_id, gtex.smtsd,
                study, gtex.smts, 
                gtex.subjid, gtex.run_acc,  
                gtex.sex, gtex.age,  gtex.dthhrdy,
                gtex.smrin, gtex.smcenter, gtex.smpthnts, gtex.smnabtchd,
                recount_qc.aligned_reads..chrm,
                recount_qc.aligned_reads..chrx,
                recount_qc.aligned_reads..chry,
                recount_qc.bc_auc.all_reads_all_bases) %>% 
  mutate(DATE = mdy(gtex.smnabtchd)) %>%
  dplyr::rename(SAMPID = external_id,
                SMTS = gtex.smts,
                SUBJID = gtex.subjid,
                SMTSD = gtex.smtsd,
                SEX = gtex.sex,
                AGE = gtex.age,
                SRA = gtex.run_acc,
                SMRIN = gtex.smrin,
                SMCENTER = gtex.smcenter) %>%
  mutate(DTHHRDY = factor(gtex.dthhrdy),
         SEX = factor(SEX),
         SEX = fct_recode(SEX, "Male" = "1", "Female" = "2"),
         SEX = factor(SEX, levels = c("Female" , "Male")),
    DTHHRDY = fct_recode(DTHHRDY, "Ventilator Case" = "0",
                                       "Violent and fast death" = "1",
                                       "Fast death of natural causes" = "2",
                                       "Intermediate death" = "3",
                                       "Slow death" = "4")) %>%
  select(SAMPID, SMTS, SMTSD, SUBJID, SEX, AGE, SMRIN, DTHHRDY, SRA, DATE)

row.names(colData) <- colData$SAMPID
head(colData)


# get countdata for this subset of colData



## colData and countData must contain the exact same samples. 
savecols <- as.character(rownames(colData)) #select the rowsname 
savecols <- as.vector(savecols) # make it a vector

countData <- assays(rse_gtex)$raw_counts %>% 
  as.data.frame() %>% 
  dplyr::select(one_of(savecols)) %>% # select just the columns 
  mutate(id_version = row.names(.)) %>%
  filter(!grepl("PAR", id_version)) %>%
  separate(id_version, into = c("id"), sep = "\\.", remove = T, extra = "drop")

row.names(countData) <- countData$id
countData$id <- NULL
 
head(countData)[1:5]
head(colData)[1:5]

# variables
dim(colData)
dim(countData)

# check that rows and samples match
head(rownames(colData) == colnames(countData))




```


```{r}
# save files for later use
write.csv(countData, file = paste("../data/countData", params$myproject, "csv", sep = "."),
              row.names = T)
write.csv(colData, file = paste("../data/colData", params$myproject, "csv", sep = "."),
              row.names = T)
```


Afterwards, gzip the large csv files.

