install.packages("tidyverse")
install.packages("rmarkdown")
install.packages('devtools')
install.packages('lubridate')
install.packages('ggpubr')
install.packages('magick')
install.packages('scales')
install.packages('Rtsne')
install.packages('cowplot')

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("recount3")
BiocManager::install("DESeq2")
BiocManager::install("biomaRt")
